FROM golang:1.25.8-alpine3.22 AS buildstage
ARG TARGETARCH
ARG TARGETOS=linux
ARG GHCR_PAT
ENV GOPRIVATE=github.com/kloudmate/*
ENV GONOSUMDB=github.com/kloudmate/*
RUN apk add --no-cache git make
RUN git config --global url."https://${GHCR_PAT}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

# eBPF modules are pre-generated by the CI runner and copied into the build context
COPY build-modules/km-ebpf /build/modules/km-ebpf

WORKDIR /app
COPY go.mod go.sum ./
COPY . .
ARG VERSION=dev
ARG COMMIT_SHA=unknown
RUN go mod tidy
RUN --mount=type=cache,target=/root/.cache/go-build \
    GOOS=${TARGETOS} GOARCH=${TARGETARCH} CGO_ENABLED=0 go build -tags kubernetes -ldflags="-w -s -X 'main.version=$VERSION' -X 'main.commit=$COMMIT_SHA'" -o kmagent ./cmd/kubeagent/main.go

FROM alpine:latest
COPY --from=buildstage /app/kmagent ./kmagent
EXPOSE 4317 4318
RUN chmod +x kmagent
ENTRYPOINT ["./kmagent"]
