apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agentServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.daemonsetName }}
  ports:
    - name: otlp-grpc-service
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http-service
      protocol: TCP
      port: 4318
      targetPort: otlp-http
  type: ClusterIP