apiVersion: v1
kind: Service
metadata:
  name: kloudmate-agent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kloudmate-agent
  ports:
    - name: otlp-grpc-service
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http-service
      protocol: TCP
      port: 4318
      targetPort: otlp-http
  type: ClusterIP