apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonsetName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.daemonsetLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      mapped-with: {{ .Values.daemonsetName }}
      {{- toYaml .Values.daemonsetLabels | nindent 6 }}
  template:
    metadata:
      labels:
        mapped-with: {{ .Values.daemonsetName }}
        {{- toYaml .Values.daemonsetLabels | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: kloudmate-km-kube-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KM_API_KEY
              value: {{ .Values.API_KEY }}
            - name: KM_COLLECTOR_ENDPOINT
              value: {{ .Values.COLLECTOR_ENDPOINT | default "https://otel.kloudmate.com:4318" }}
            - name: KM_CONFIG_CHECK_INTERVAL
              value: {{ .Values.KM_CONFIG_CHECK_INTERVAL | default "30s" }}
              ## for daemonset
            - name: CONFIGMAP_DAEMONSET_NAME
              value: {{ .Values.configMapDaemonset.name }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
              ## for daemonset 
            - name: agent-config-volume-daemonset
              mountPath: "/etc/kmagent/agent-daemonset.yaml"
              readOnly: true
              subPath: "agent.yaml"
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: rootfs
              mountPath: /host
              readOnly: true
      volumes:
        - name: agent-config-volume-daemonset
          configMap:
            ## for daemonset
            name: {{ .Values.configMapDaemonset.name }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: rootfs
          hostPath:
            path: /