apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonsetName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "km-kube-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.daemonsetName }}
      {{- include "km-kube-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.daemonsetName }}
        {{- include "km-kube-agent.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: kloudmate-km-kube-agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: KM_API_KEY
              value: {{ .Values.API_KEY }}
            - name: KM_COLLECTOR_ENDPOINT
              value: {{ .Values.COLLECTOR_ENDPOINT | default "https://otel.kloudmate.com:4318" }}
            - name: KM_CONFIG_CHECK_INTERVAL
              value: {{ .Values.KM_CONFIG_CHECK_INTERVAL | default "30s" }}
            - name: CONFIGMAP_NAME
              value: {{ .Values.configMap.name }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
          volumeMounts:
            - name: agent-config-volume
              mountPath: "/etc/kmagent/agent.yaml"
              readOnly: true
              subPath: "agent.yaml"
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: rootfs
              mountPath: /host
              readOnly: true
      volumes:
        - name: agent-config-volume
          configMap:
            # Assumes the ConfigMap is also managed by this chart
            name: {{ .Values.configMap.name }}
        - name: varlog
          hostPath:
            path: /var/log
        - name: rootfs
          hostPath:
            path: /