apiVersion: apps/v1
kind: Deployment
metadata:
  name: kloudmate-config-updater
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kloudmate-config-updater
spec:
  # replica is 1 to ensure a single instance is running
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kloudmate-config-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kloudmate-config-updater
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}

      containers:
        - name: config-updater
          image: "{{ .Values.configUpdater.image.repository }}:{{ .Values.configUpdater.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.configUpdater.image.pullPolicy }}

          env:
            - name: KM_API_KEY
              value: {{ .Values.API_KEY }}
            - name: KM_COLLECTOR_ENDPOINT
              value: {{ .Values.COLLECTOR_ENDPOINT | default "https://otel.kloudmate.com:4318" }}
            - name: KM_CONFIG_CHECK_INTERVAL
              value: {{ .Values.KM_CONFIG_CHECK_INTERVAL | default "30s" }}
            - name: KM_UPDATE_ENDPOINT
              value: {{ .Values.KM_UPDATE_ENDPOINT | default "https://api.kloudmate.com/agents/config-check" }}
              ## for daemonset
            - name: CONFIGMAP_DAEMONSET_NAME
              value: {{ .Values.configMapDaemonset.name }}
              ## for deployment
            - name: CONFIGMAP_DEPLOYMENT_NAME
              value: {{ .Values.configMapDeployment.name }}
            - name: KM_CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: KM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KM_DAEMONSET_NAME
              value: {{ .Values.daemonsetName }}
            - name: KM_DEPLOYMENT_NAME
              value: {{ .Values.deploymentName }}

          volumeMounts:
              ## for daemonset 
            - name: agent-config-volume-daemonset
              mountPath: "/etc/kmagent/agent-daemonset.yaml"
              readOnly: true
              subPath: "agent.yaml"
              ## for deployment
            - name: agent-config-volume-deployment
              mountPath: "/etc/kmagent/agent-deployment.yaml"
              readOnly: true
              subPath: "agent.yaml"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

      volumes:
        - name: agent-config-volume-daemonset
          configMap:
            ## for daemonset
            name: {{ .Values.configMapDaemonset.name }}
        - name: agent-config-volume-deployment
          configMap:
            ## for deployment
            name: {{ .Values.configMapDeployment.name }}