apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: {{ .Values.InstrumentationCrd.name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  exporter:
    endpoint: http://{{ .Values.agentServiceName }}.{{ .Release.Namespace }}.svc.cluster.local:4318
  
  propagators:
    - tracecontext
    - baggage
    - b3
    
  sampler:
    type: parentbased_traceidratio
    argument: "1"

  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
  
  env:    
    # Using the Downward API to dynamically set resource attributes for the pod.
    - name: POD_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    - name: NAMESPACE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: SERVICE_ACCOUNT_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
          
