# This config file will be used by the KM-Agent on it's first initialization in docker mode.

receivers:
  docker_stats:
    collection_interval: 2s
    timeout: 20s
    metrics:
      container.cpu.usage.system:
        enabled: true
      container.memory.total_rss:
        enabled: true

  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
  otlphttp:
    endpoint: https://otel.kloudmate.com:4318
    headers:
        Authorization: <KM_API_KEY>

processors:
  batch:

extensions:
  zpages:
    endpoint: :55679

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]