# This config file will be used by the KM-Agent on it's first initialization in docker mode.

receivers:
  docker_stats:
    collection_interval: 10s
    timeout: 20s
    metrics:
      container.cpu.usage.system:
        enabled: true
      container.memory.total_rss:
        enabled: true

  hostmetrics:
    root_path: /hostfs
    collection_interval: 25s
    scrapers:
      cpu:
         metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      processes:
      process:
       metrics:
          process.cpu.utilization:
            enabled: true
          process.memory.utilization:
            enabled: true
       mute_process_all_errors: true
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      filesystem:
         metrics:
          system.filesystem.usage:
            enabled: true
          system.filesystem.utilization:
            enabled: true
      load:
         cpu_average: true
      paging:

  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    sending_queue:
      enabled: true
      num_consumers: 10 # Increase to process more items in parallel
      queue_size: 10000 # Increase queue size to handle bursts
    endpoint: ${env:KM_COLLECTOR_ENDPOINT}
    headers:
        Authorization: ${env:KM_API_KEY}

processors:
  batch:

extensions:
  # zpages:
  #   endpoint: :55679

service:
  # extensions: [zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics, docker_stats]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]
