#!/usr/bin/expect -f
set timeout -1
set rpm_file [lindex $argv 0]
set gpg_name [lindex $argv 1]
set passphrase [lindex $argv 2]

set env(GPG_TTY) /dev/tty
set env(PINENTRY_MODE) loopback

spawn bash -c "rpmsign --define \"_gpg_name $gpg_name\" --resign $rpm_file"

expect {
    -nocase -re "pass *phrase" {
        send "$passphrase\r"
    }
    timeout {
        puts "Timeout waiting for passphrase prompt"
        exit 1
    }
}
expect eof
