# name: Test KmAgent
# on: ["push"]
# jobs:
#   checks:
#     runs-on: ubuntu-latest
#     steps:

#       - uses: actions/checkout@v4
#       - name: Setup Go
#         uses: actions/setup-go@v4
#         with:
#           go-version: "1.23.x"

#       - name: Verify Dependencies
#         run: go mod verify
          
#       - name: Test KmAgent
#         run: go test ./...
    