name: Release Helm Chart

on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # `fetch-depth: 0` is crucial for chart-releaser to get the full Git history.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      # This single action handles linting, dependency building,
      # chart packaging, creating a GitHub release, and updating the index.
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          lint: true
          # `dep-update` is enabled to automatically run `helm dependency update`.
          dep-update: true
          charts_dir: deployment/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
