name: Docker Image Bulid For Docker Registry

on:
  push

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Push Image
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} registry-1.docker.io
          docker build . --tag kloudmate/km-agent:latest
          docker push kloudmate/km-agent:latest