name: Release Helm Chart

on:
  release:
    types: [created]

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Full history needed for chart-releaser to diff versions
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      # Install yq
      - name: Install yq
        run: |
          YQ_VERSION="v4.40.5"
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      # Update chart version and push to develop
      - name: Update Chart Version
        run: |
          NEW_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          
          yq e '.version = "'"$NEW_VERSION"'"' -i deployment/helm/km-kube-agent/Chart.yaml
          yq e '.appVersion = "'"$NEW_VERSION"'"' -i deployment/helm/km-kube-agent/Chart.yaml

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add deployment/helm/km-kube-agent/Chart.yaml
          git commit -m "chore(release): update chart version to $NEW_VERSION"

          git push https://x-access-token:${{ secrets.GHCR_PAT }}@github.com/kloudmate/km-agent.git HEAD:${{ github.event.release.target_commitish }}

      # Add external Helm repositories (optional)
      - name: Add external Helm repositories
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts

      # Package and release charts to gh-pages
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: deployment/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
