name: Publish kubernetes agent image to the registry

on:
  release:
    types: [created]

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & Push Image
        run: |
          docker login --username kloudmate --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build . -f .\kube.Dockerfile --tag ghcr.io/kloudmate/km-kube-agent:latest
          docker push ghcr.io/kloudmate/km-kube-agent:latest