name: Release Helm Chart

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Install yq
        run: |
          YQ_VERSION="v4.40.5"
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
      
      - name: Add external Helm repositories
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts

      - name: Update Chart Dependencies and Version
        id: vars
        run: |
          NEW_VERSION=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          CHART_PATH="deployment/helm/km-kube-agent"

          helm dependency update "${CHART_PATH}"

          yq e '.version = "'"$NEW_VERSION"'"' -i "${CHART_PATH}/Chart.yaml"
          yq e '.appVersion = "'"$NEW_VERSION"'"' -i "${CHART_PATH}/Chart.yaml"
          
          CHART_VERSION=$(yq e '.version' "${CHART_PATH}/Chart.yaml")
          APP_VERSION=$(yq e '.appVersion' "${CHART_PATH}/Chart.yaml")
          echo "CHART_PATH=${CHART_PATH}" >> "$GITHUB_OUTPUT"
          echo "CHART_VERSION=${CHART_VERSION}" >> "$GITHUB_OUTPUT"
          echo "APP_VERSION=${APP_VERSION}" >> "$GITHUB_OUTPUT"
          cat "$[INFO] : using path - {CHART_PATH}/Chart.yaml"

      - name: Package Helm Chart
        run: |
          # Create the Helm chart package
          helm package ${{ steps.vars.outputs.CHART_PATH }}
          PACKAGE_NAME="km-kube-agent-${{ steps.vars.outputs.CHART_VERSION }}.tgz"
          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> "$GITHUB_OUTPUT"
          echo "Package created: ${PACKAGE_NAME}"

      - name: Upload Helm Chart to GitHub Release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.vars.outputs.PACKAGE_NAME }}
          asset_name: ${{ steps.vars.outputs.PACKAGE_NAME }}
          asset_content_type: application/gzip
          
      - name: Update Helm GH-Pages with Versions
        run: |
          # Use sed to replace the placeholders with the actual version numbers
          sed -i "s/{{ APP_VERSION }}/${{ steps.vars.outputs.APP_VERSION }}/g" index.html
          sed -i "s/{{ CHART_VERSION }}/${{ steps.vars.outputs.CHART_VERSION }}/g" index.html

      - name: Sync Helm Chart Repository Index on gh-pages branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

          mv ./${{ steps.vars.outputs.PACKAGE_NAME }} .
          mv ./index.html .

          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.repository }}/

          git add .
          git commit -m "🚀 chore(release): update index manifest for km-kube-agent ${{ steps.vars.outputs.CHART_VERSION }}" || echo "No changes to commit"
          git push origin gh-pages
